import { auth, db, storage, call, onAuthStateChanged, signOut, getIdToken, ref, get, set, update, push, remove, query, orderByChild, equalTo, storageRef, uploadBytes, getDownloadURL } from './firebase.js';

const $=id=>document.getElementById(id); const page=location.pathname.split('/').pop();
const pageRole={owner.html:'OWNER',admin.html:'ADMIN',subadmin.html:'SUB-ADMIN',student.html:'STUDENT'};
let me=null,profile=null,role=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const read=async path=>{const s=await get(ref(db,path));return s.exists()?s.val():null};
const entries=v=>Object.entries(v||{}).map(([id,x])=>({id,...(x||{})}));
const toast=(t,kind='')=>{const el=$('toast');el.textContent=t;el.className=`toast ${kind}`;setTimeout(()=>{el.textContent='';el.className='toast'},3500)};
const audit=async(action,targetType,targetId,oldValue=null,newValue=null)=>{if(role!=='OWNER')return;const id=push(ref(db,'auditLogs')).key;await set(ref(db,`auditLogs/${id}`),{performedBy:me.uid,performedByRole:role,action,targetType,targetId,oldValue,newValue,timestamp:Date.now()})};
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">لا توجد بيانات</td></tr>`}</tbody></table></div>`;
const form=(title,body)=>`<div class="modal-panel"><h3>${title}</h3>${body}</div>`;

async function loadStudents(){
  if(role==='OWNER') return entries(await read('students'));
  if(role==='STUDENT') {const s=await read(`students/${me.uid}`);return s?[{id:me.uid,...s}]:[];}
  const index=role==='ADMIN'?await read(`adminScopes/${me.uid}/schools`):null;
  const schoolIds=role==='ADMIN'?Object.keys(index||{}).filter(k=>index[k]===true):[profile.groupId];
  const ids=new Set();
  for(const schoolId of schoolIds){const idx=await read(`schoolStudents/${schoolId}`); if(idx) Object.keys(idx).forEach(id=>ids.add(id));}
  const out=[];for(const id of ids){const s=await read(`students/${id}`);if(s && (role!=='SUB-ADMIN'||s.groupId===profile.groupId))out.push({id,...s});}return out;
}

async function overview(){
  if(role==='STUDENT'){
    const s=await read(`students/${me.uid}`), sessions=entries(await read('attendanceSessions')), grades=entries(await get(query(ref(db,'grades'),orderByChild('studentId'),equalTo(me.uid))).then(x=>x.exists()?x.val():{}));
    let total=0,present=0; for(const ses of sessions.filter(x=>x.groupId===profile.groupId)){const r=await read(`attendance/${ses.id}/${me.uid}`);if(r){total++;if(r.status==='PRESENT'||r.status==='LATE')present++;}}
    const pct=total?Math.round(present/total*100):0;
    $('view').innerHTML=`<div class="section-head"><div><span class="eyebrow">STUDENT</span><h1>مرحبًا ${esc(profile.name)}</h1></div></div><div class="stats">${[['نسبة الحضور',pct+'%'],['جلسات مسجلة',total],['المواد المسجلة',Object.keys(s?.subjects||{}).length],['الدرجات',grades.length]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>${table(['البيان','القيمة'],[['الاسم',s?.name],['الكود',s?.studentCode||'—'],['المجموعة',s?.groupId||'—'],['العام الدراسي',s?.academicYear||'—'],['الحالة',s?.status]])}`;return;
  }
  const [students,schools,groups,subjects]=await Promise.all([loadStudents(),read('schools'),read('groups'),read('subjects')]);
  $('view').innerHTML=`<div class="section-head"><div><span class="eyebrow">${role}</span><h1>لوحة التحكم</h1></div></div><div class="stats">${[['الطلاب',students.length],['المدارس',role==='OWNER'?entries(schools).length:'—'],['المجموعات',role==='OWNER'?entries(groups).length:'—'],['المواد',role==='OWNER'?entries(subjects).length:'—']].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div class="panel"><h2>النظام متصل</h2><p>Firebase Authentication + Realtime Database${role==='OWNER'?' + Storage':''} يعملان من نفس المشروع.</p></div>`;
}

async function students(){
  const data=await loadStudents();
  if(role==='STUDENT'){const s=data[0]||{};$('view').innerHTML=`<h1>ملفي</h1>${table(['الحقل','القيمة'],Object.entries(s).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(typeof v==='object'?JSON.stringify(v):v)}</td></tr>`))}`;return;}
  $('view').innerHTML=`<div class="section-head"><h1>الطلاب</h1>${['OWNER','ADMIN'].includes(role)?'<button class="btn" id="addStudent">إضافة طالب</button>':''}</div>${table(['الكود','الاسم','الهاتف','المدرسة','المجموعة','الحالة','إجراء'],data.map(s=>`<tr><td>${esc(s.studentCode||'—')}</td><td>${esc(s.name)}</td><td>${esc(s.phone)}</td><td>${esc(s.schoolId||'—')}</td><td>${esc(s.groupId||'—')}</td><td>${esc(s.status)}</td><td>${role==='OWNER'&&s.status==='PENDING'?`<button class="mini approve" data-id="${s.id}">اعتماد</button> <button class="mini reject" data-id="${s.id}">رفض</button>`:'—'}</td></tr>`))}`;
  document.querySelectorAll('.approve').forEach(b=>b.onclick=async()=>{const s=data.find(x=>x.id===b.dataset.id);const schoolId=prompt('schoolId',s.schoolId||'');const groupId=prompt('groupId',s.groupId||'');if(!schoolId||!groupId)return;try{await call('approveStudent')({studentId:s.id,schoolId,groupId});toast('تم اعتماد الطالب');students();}catch(e){toast(e.message,'error')}});
  document.querySelectorAll('.reject').forEach(b=>b.onclick=async()=>{try{await call('rejectStudent')({studentId:b.dataset.id});toast('تم رفض الطالب');students();}catch(e){toast(e.message,'error')}});
  $('addStudent')?.addEventListener('click',()=>addStudentForm());
}
async function addStudentForm(){const schools=entries(await read('schools')),groups=entries(await read('groups'));$('view').insertAdjacentHTML('beforeend',form('إضافة طالب',`<form id="studentForm"><label>الاسم<input id="n" required></label><label>الهاتف<input id="p" required></label><label>البريد<input id="e" type="email" required></label><label>كلمة المرور<input id="pw" type="password" minlength="8" required></label><label>المدرسة<select id="sc">${schools.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label>المجموعة<select id="gr">${groups.map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join('')}</select></label><button class="btn">إنشاء طلب</button></form>`));$('studentForm').onsubmit=async e=>{e.preventDefault();try{await call('createStudentByAdmin')({name:$('n').value.trim(),phone:$('p').value.trim(),email:$('e').value.trim(),password:$('pw').value,schoolId:$('sc').value,groupId:$('gr').value});toast('تم إنشاء الطالب كطلب Pending');students()}catch(err){toast(err.message,'error')}}}

async function schools(){if(role!=='OWNER')return denied();const data=entries(await read('schools'));$('view').innerHTML=`<div class="section-head"><h1>المدارس</h1><button class="btn" id="add">إضافة</button></div>${table(['المعرف','الاسم','الحالة','إجراء'],data.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td>${esc(x.status||'ACTIVE')}</td><td><button class="mini del" data-id="${x.id}">حذف</button></td></tr>`))}`;simpleAdd('schools',['name']);}
async function groups(){if(role!=='OWNER')return denied();const data=entries(await read('groups'));$('view').innerHTML=`<div class="section-head"><h1>المجموعات</h1><button class="btn" id="add">إضافة</button></div>${table(['المعرف','الاسم','المدرسة','الحالة','إجراء'],data.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td>${esc(x.schoolId)}</td><td>${esc(x.status||'ACTIVE')}</td><td><button class="mini del" data-id="${x.id}">حذف</button></td></tr>`))}`;simpleAdd('groups',['name','schoolId']);}
async function subjects(){if(role!=='OWNER')return denied();const data=entries(await read('subjects'));$('view').innerHTML=`<div class="section-head"><h1>المواد</h1><button class="btn" id="add">إضافة</button></div>${table(['المعرف','الاسم','الكود','المدرس','المجموعة','إجراء'],data.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td>${esc(x.code||'—')}</td><td>${esc(x.teacherId||'—')}</td><td>${esc(x.groupId||'—')}</td><td><button class="mini del" data-id="${x.id}">حذف</button></td></tr>`))}`;simpleAdd('subjects',['name','code','teacherId','schoolId','groupId']);}
async function simpleAdd(collection,fields){$('add').onclick=()=>{$('view').insertAdjacentHTML('beforeend',form('إضافة',`<form id="addForm">${fields.map(f=>`<label>${esc(f)}<input id="f_${esc(f)}" required></label>`).join('')}<button class="btn">حفظ</button></form>`));$('addForm').onsubmit=async e=>{e.preventDefault();const id=push(ref(db,collection)).key,d={status:'ACTIVE',createdAt:Date.now(),createdBy:me.uid};fields.forEach(f=>d[f]=$('f_'+f).value.trim());await set(ref(db,`${collection}/${id}`),d);await audit('CREATE',collection,id,null,d);toast('تم الحفظ');route(collection)}};document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(!confirm('حذف؟'))return;await remove(ref(db,`${collection}/${b.dataset.id}`));await audit('DELETE',collection,b.dataset.id);route(collection)})}
function denied(){$('view').innerHTML='<div class="panel"><h2>غير مصرح</h2><p>هذه الوظيفة متاحة للـOwner فقط.</p></div>'}

async function attendance(){
  if(role==='STUDENT'){
    const sessions=entries(await read('attendanceSessions')).filter(x=>x.groupId===profile.groupId),rows=[];for(const s of sessions){const r=await read(`attendance/${s.id}/${me.uid}`);rows.push(`<tr><td>${esc(s.date)}</td><td>${esc(s.subjectId)}</td><td>${esc(r?.status||'لم يسجل')}</td></tr>`)}$('view').innerHTML=`<h1>حضوري</h1>${table(['التاريخ','المادة','الحالة'],rows)}`;return;
  }
  const sessions=entries(await read('attendanceSessions')).filter(s=>role==='OWNER'||(role==='SUB-ADMIN'?s.groupId===profile.groupId:true));const students=await loadStudents();
  $('view').innerHTML=`<div class="section-head"><h1>الحضور</h1>${role!=='STUDENT'?'<button class="btn" id="newSession">جلسة جديدة</button>':''}</div>${table(['الجلسة','التاريخ','المادة','المجموعة','الحالة','تسجيل'],sessions.map(s=>`<tr><td>${esc(s.id)}</td><td>${esc(s.date)}</td><td>${esc(s.subjectId)}</td><td>${esc(s.groupId)}</td><td>${esc(s.status)}</td><td><button class="mini record" data-id="${s.id}">فتح</button></td></tr>`))}`;
  $('newSession')?.addEventListener('click',async()=>{const subjectId=prompt('subjectId'),groupId=prompt('groupId'),schoolId=prompt('schoolId'),date=prompt('YYYY-MM-DD',new Date().toISOString().slice(0,10)),startTime=prompt('startTime','09:00'),endTime=prompt('endTime','11:00');if(!subjectId||!groupId||!schoolId)return;try{await call('createAttendanceSession')({subjectId,groupId,schoolId,date,startTime,endTime});toast('تم إنشاء الجلسة');attendance()}catch(e){toast(e.message,'error')}});
  document.querySelectorAll('.record').forEach(b=>b.onclick=()=>recordForSession(b.dataset.id,students));
}
async function recordForSession(sessionId,students){$('view').insertAdjacentHTML('beforeend',form('تسجيل الحضور',`<div class="record-list">${students.map(s=>`<div class="record-row"><span>${esc(s.name)}</span><select id="a_${s.id}"><option value="PRESENT">حاضر</option><option value="ABSENT">غائب</option><option value="LATE">متأخر</option></select><button class="mini save" data-st="${s.id}">حفظ</button></div>`).join('')}</div>`));document.querySelectorAll('.save').forEach(b=>b.onclick=async()=>{try{await call('recordAttendance')({sessionId,studentId:b.dataset.st,status:$('a_'+b.dataset.st).value});b.disabled=true;b.textContent='تم';toast('تم التسجيل')}catch(e){toast(e.message,'error')}})}

async function grades(){
  let data=[];
  if(role==='STUDENT'){const s=await get(query(ref(db,'grades'),orderByChild('studentId'),equalTo(me.uid)));data=entries(s.exists()?s.val():{});}else if(role==='OWNER'){data=entries(await read('grades'));}else{const students=await loadStudents();for(const st of students){const s=await get(query(ref(db,'grades'),orderByChild('studentId'),equalTo(st.id)));if(s.exists())data.push(...entries(s.val()));}}
  $('view').innerHTML=`<div class="section-head"><h1>الدرجات</h1>${role==='OWNER'?'<button class="btn" id="addGrade">إضافة درجة</button>':''}</div>${table(['الطالب','المادة','أعمال السنة','الاختبار','النهائي','النسبة','التقدير','النتيجة','الحالة'],data.map(g=>`<tr><td>${esc(g.studentId)}</td><td>${esc(g.subjectId)}</td><td>${g.coursework??0}</td><td>${g.exam??0}</td><td>${g.final??0}</td><td>${g.percentage??0}</td><td>${esc(g.grade||'—')}</td><td>${esc(g.result||'—')}</td><td>${esc(g.status||'—')}</td></tr>`))}`;
  $('addGrade')?.addEventListener('click',()=>{$('view').insertAdjacentHTML('beforeend',form('إضافة درجة',`<form id="gradeForm">${['studentId','subjectId','coursework','exam','final','percentage','grade'].map(f=>`<label>${f}<input id="g_${f}" required></label>`).join('')}<label>result<select id="g_result"><option>PASS</option><option>FAIL</option></select></label><button class="btn">حفظ</button></form>`));$('gradeForm').onsubmit=async e=>{e.preventDefault();const id=push(ref(db,'grades')).key,d={studentId:$('g_studentId').value.trim(),subjectId:$('g_subjectId').value.trim(),coursework:+$('g_coursework').value,exam:+$('g_exam').value,final:+$('g_final').value,percentage:+$('g_percentage').value,grade:$('g_grade').value.trim(),result:$('g_result').value,status:'APPROVED',createdBy:me.uid,createdAt:Date.now()};await set(ref(db,`grades/${id}`),d);await audit('CREATE','GRADE',id,null,d);toast('تم حفظ الدرجة');grades()}})}

async function reports(){if(role==='STUDENT'){const sessions=entries(await read('attendanceSessions')).filter(s=>s.groupId===profile.groupId);let p=0,a=0,l=0;for(const s of sessions){const r=await read(`attendance/${s.id}/${me.uid}`);if(r?.status==='PRESENT')p++;else if(r?.status==='LATE')l++;else if(r?.status==='ABSENT')a++;}const total=p+a+l;$('view').innerHTML=`<h1>تقارير الحضور</h1><div class="stats">${[['حاضر',p],['متأخر',l],['غائب',a],['النسبة',total?Math.round((p+l)/total*100)+'%':'0%'].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>`;return}const data=entries(await read('attendance'));const p=data.filter(x=>x.status==='PRESENT').length,l=data.filter(x=>x.status==='LATE').length,a=data.filter(x=>x.status==='ABSENT').length,total=p+l+a;$('view').innerHTML=`<h1>التقارير</h1><div class="stats">${[['حاضر',p],['متأخر',l],['غائب',a],['النسبة',total?Math.round((p+l)/total*100)+'%':'0%'].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>`}
async function notifications(){const data=entries(await read('notifications')).filter(n=>role==='OWNER'||n.targetUserId===me.uid);$('view').innerHTML=`<h1>الإشعارات</h1>${table(['العنوان','المحتوى','التاريخ'],data.reverse().map(n=>`<tr><td>${esc(n.title)}</td><td>${esc(n.body)}</td><td>${new Date(n.createdAt||0).toLocaleString('ar-EG')}</td></tr>`))}`}
async function filesView(){const data=entries(await read('files'));$('view').innerHTML=`<div class="section-head"><h1>الملفات</h1>${role==='OWNER'?'<input type="file" id="fileInput" accept=".pdf,.doc,.docx,image/*,video/*"><button class="btn" id="upload">رفع</button>':''}</div>${table(['الاسم','النوع','الرابط'],data.map(f=>`<tr><td>${esc(f.name)}</td><td>${esc(f.contentType||f.type)}</td><td>${f.url?`<a class="btn" href="${esc(f.url)}" target="_blank" rel="noopener">فتح</a>`:'—'}</td></tr>`))}`;if(role==='OWNER')$('upload').onclick=async()=>{const f=$('fileInput').files[0];if(!f)return;try{await getIdToken(me,true);const path=`uploads/${Date.now()}_${f.name.replace(/[^\w.\-]/g,'_')}`;const sr=storageRef(storage,path);await uploadBytes(sr,f);const url=await getDownloadURL(sr),id=push(ref(db,'files')).key,d={name:f.name,contentType:f.type,path,url,uploadedBy:me.uid,uploadedByRole:'OWNER',status:'ACTIVE',createdAt:Date.now()};await set(ref(db,`files/${id}`),d);await audit('UPLOAD','FILE',id,null,d);toast('تم الرفع');filesView()}catch(e){toast(e.message,'error')}}}
async function admins(){if(role!=='OWNER')return denied();const users=entries(await read('users')).filter(u=>['ADMIN','SUB-ADMIN'].includes(u.role));$('view').innerHTML=`<div class="section-head"><h1>المستخدمون الإداريون</h1><button class="btn" id="newSub">إضافة Sub-Admin</button></div>${table(['الاسم','البريد','الدور','الحالة'],users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.role}</td><td>${u.status}</td></tr>`))}<div class="panel"><h3>اعتماد طلبات Admin</h3>${entries(await read('adminRequests')).filter(x=>x.status==='PENDING').map(r=>`<div class="request"><b>${esc(r.name)}</b> — ${esc(r.email)} <button class="mini apr" data-id="${r.id}">اعتماد</button></div>`).join('')||'<p>لا توجد طلبات.</p>'}</div>`;document.querySelectorAll('.apr').forEach(b=>b.onclick=async()=>{const pw=prompt('كلمة مرور الحساب الجديد (8 أحرف على الأقل)');if(!pw)return;try{await call('approveAdminRequest')({requestId:b.dataset.id,password:pw});toast('تم إنشاء Admin');admins()}catch(e){toast(e.message,'error')}});$('newSub').onclick=async()=>{const name=prompt('الاسم'),email=prompt('البريد'),phone=prompt('الهاتف'),password=prompt('كلمة المرور'),schoolId=prompt('schoolId'),groupId=prompt('groupId');if(!name||!email||!password||!schoolId||!groupId)return;try{await call('createSubAdmin')({name,email,phone:phone||'',password,schoolId,groupId});toast('تم إنشاء Sub-Admin');admins()}catch(e){toast(e.message,'error')}}}
async function settings(){if(role!=='OWNER')return denied();const s=await read('settings')||{};$('view').innerHTML=`<h1>الإعدادات</h1><form id="settingsForm" class="panel">${['platformName','logo','contactPhone','contactEmail','address','departmentHead','doctors','academicYear'].map(k=>`<label>${k}<input id="set_${k}" value="${esc(s[k]||'')}"></label>`).join('')}<label>maintenanceMode<select id="set_maintenanceMode"><option value="false">Off</option><option value="true" ${s.maintenanceMode?'selected':''}>On</option></select></label><button class="btn">حفظ</button></form>`;$('settingsForm').onsubmit=async e=>{e.preventDefault();const d={};['platformName','logo','contactPhone','contactEmail','address','departmentHead','doctors','academicYear'].forEach(k=>d[k]=$('set_'+k).value.trim());d.maintenanceMode=$('set_maintenanceMode').value==='true';const old={...s};await update(ref(db,'settings'),d);await audit('UPDATE','SETTINGS','global',old,d);toast('تم الحفظ')}}
async function auditView(){if(role!=='OWNER')return denied();const data=entries(await read('auditLogs')).sort((a,b)=>(b.timestamp||0)-(a.timestamp||0));$('view').innerHTML=`<h1>سجل التدقيق</h1>${table(['العملية','النوع','المعرف','الدور','الوقت'],data.slice(0,300).map(x=>`<tr><td>${esc(x.action)}</td><td>${esc(x.targetType)}</td><td>${esc(x.targetId)}</td><td>${esc(x.performedByRole)}</td><td>${new Date(x.timestamp||0).toLocaleString('ar-EG')}</td></tr>`))}`}

const routes={overview,students,schools,groups,subjects,attendance,grades,reports,notifications,files:filesView,admins,settings,audit:auditView};
function bind(){document.querySelectorAll('#side [data-view]').forEach(b=>b.onclick=()=>route(b.dataset.view));}
function route(v){(routes[v]||overview)().catch(e=>toast(e.message||'تعذر تحميل الصفحة','error'));}

onAuthStateChanged(auth,async user=>{if(!user){location.href='auth.html';return}me=user;profile=await read(`users/${user.uid}`);if(!profile||profile.status!=='ACTIVE'){await signOut(auth);location.href='auth.html';return}role=profile.role;if(pageRole[page]!==role){location.href=role==='OWNER'?'owner.html':role==='ADMIN'?'admin.html':role==='SUB-ADMIN'?'subadmin.html':'student.html';return}$('userName').textContent=profile.name||user.email;try{await call('refreshClaims')();await getIdToken(me,true)}catch{}$('logout').onclick=()=>signOut(auth).then(()=>location.href='auth.html');bind();document.querySelector('#side [data-view="overview"]')?.classList.add('active');route('overview');});
